"""
GitHub Manager Agent
Modifies code on GitHub based on Elina's requests.
Uses GitHub API + PAT to commit changes.
"""
from .base import Agent
from datetime import datetime
import os, json, base64, requests

class GitHubManager(Agent):
    def __init__(self):
        super().__init__("GitHubManager", "Manages GitHub repo: add/remove/update agents")
        self.owner = os.environ.get("GITHUB_REPO_OWNER","")
        self.repo = os.environ.get("GITHUB_REPO_NAME","elina-radman")
        self.token = os.environ.get("GH_PAT","")
        self.api = "https://api.github.com"
    
    def _headers(self):
        return {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json"
        }
    
    def run(self, action=None, **kwargs):
        self.runs += 1
        self.last_run = datetime.now().isoformat()
        if not self.token:
            return {"error": "No GH_PAT set"}
        action = action or kwargs.get("command","list_agents")
        actions = {
            "list_agents": self.list_agents,
            "add_agent": self.add_agent,
            "remove_agent": self.remove_agent,
            "update_file": self.update_file,
            "get_file": self.get_file,
            "list_files": self.list_files,
            "status": self.repo_status,
        }
        fn = actions.get(action)
        if fn:
            return fn(**kwargs)
        return {"error": f"Unknown action: {action}", "available": list(actions.keys())}
    
    def repo_status(self, **kw):
        url = f"{self.api}/repos/{self.owner}/{self.repo}"
        r = requests.get(url, headers=self._headers())
        if r.status_code == 200:
            d = r.json()
            return {"name": d["full_name"], "stars": d["stargazers_count"],
                    "updated": d["updated_at"], "url": d["html_url"]}
        return {"error": r.status_code, "msg": r.text[:200]}
    
    def list_files(self, path="", **kw):
        url = f"{self.api}/repos/{self.owner}/{self.repo}/contents/{path}"
        r = requests.get(url, headers=self._headers())
        if r.status_code == 200:
            return [{"name": f["name"], "type": f["type"], "path": f["path"]} for f in r.json()]
        return {"error": r.status_code}
    
    def get_file(self, path, **kw):
        url = f"{self.api}/repos/{self.owner}/{self.repo}/contents/{path}"
        r = requests.get(url, headers=self._headers())
        if r.status_code == 200:
            d = r.json()
            content = base64.b64decode(d["content"]).decode()
            return {"path": path, "content": content, "sha": d["sha"]}
        return {"error": r.status_code}
    
    def update_file(self, path, content, message=None, **kw):
        url = f"{self.api}/repos/{self.owner}/{self.repo}/contents/{path}"
        # Get current SHA
        r = requests.get(url, headers=self._headers())
        sha = r.json().get("sha","") if r.status_code == 200 else ""
        
        data = {
            "message": message or f"✏️ Update {path} via ElinaOS",
            "content": base64.b64encode(content.encode()).decode(),
            "branch": "main",
        }
        if sha:
            data["sha"] = sha
        
        r2 = requests.put(url, headers=self._headers(), json=data)
        if r2.status_code in [200, 201]:
            return {"status": "updated", "path": path}
        return {"error": r2.status_code, "msg": r2.text[:300]}
    
    def add_agent(self, name, description, code, **kw):
        path = f"agents/{name.lower().replace(' ','_')}.py"
        content = f'''"""Agent: {name} — {description}
Generated by ElinaOS GitHubManager
"""
from .base import Agent
from datetime import datetime

class {name.replace(" ","")}(Agent):
    def __init__(self):
        super().__init__("{name}", "{description}")
    
    def run(self, **kwargs):
        self.runs += 1
        self.last_run = datetime.now().isoformat()
        # Agent logic here
        {code or "pass"}
        return {{"status": "ok"}}
'''
        return self.update_file(path, content, f"➕ Add agent: {name}")
    
    def remove_agent(self, name, **kw):
        path = f"agents/{name.lower().replace(' ','_')}.py"
        url = f"{self.api}/repos/{self.owner}/{self.repo}/contents/{path}"
        r = requests.get(url, headers=self._headers())
        if r.status_code != 200:
            return {"error": "Agent not found"}
        sha = r.json()["sha"]
        data = {"message": f"➖ Remove agent: {name}", "sha": sha, "branch": "main"}
        r2 = requests.delete(url, headers=self._headers(), json=data)
        if r2.status_code == 200:
            return {"status": "removed", "agent": name}
        return {"error": r2.status_code}
    
    def list_agents(self, **kw):
        url = f"{self.api}/repos/{self.owner}/{self.repo}/contents/agents"
        r = requests.get(url, headers=self._headers())
        if r.status_code == 200:
            agents = [f["name"].replace(".py","") for f in r.json() 
                     if f["name"].endswith(".py") and f["name"] != "__init__.py" and f["name"] != "base.py"]
            return {"agents": agents, "count": len(agents)}
        return {"error": r.status_code}
